Linear Algebra and Probability

In [38]:
import pandas as pd
import numpy as np

1. Load the dataset and handle any missing data by replacing null values with the mean value of the respective column

In [39]:
df=pd.read_csv("winequality-red.csv",sep=';')
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [40]:
df=df.fillna(df.mean(numeric_only=True))
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [41]:
print(df.isnull().sum())

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

2. Extract the following columns as vectors: alcohol,citric acid.

In [42]:
alcohol=df["alcohol"].values
print("Alcohol vector:")
print(alcohol)

Alcohol vector:
[ 9.4  9.8  9.8 ... 11.  10.2 11. ]

In [43]:
citric_acid=df["citric acid"].values
print("Citric Acid vector:")
print(citric_acid)

Citric Acid vector:
[0.   0.   0.04 ... 0.13 0.12 0.47]

3. Select two features (e.g., alcohol and density) from the dataset and calculate the covariance matrix using np.cov(X.T), where X is the feature matrix consisting of the selected columns

In [44]:
X=df[['alcohol','density']].values
cov_matrix=np.cov(X.T)
print("Covariance Matrix:")
print(cov_matrix)

Covariance Matrix:
[[ 1.13564740e+00 -9.97951790e-04]
 [-9.97951790e-04  3.56202945e-06]]

4. Perform eigen decomposition on the covariance matrix you computed in question 3. Identify and interpret the results:Identify the top 2 eigenvalues of the covariance matrix,Identify the corresponding eigenvectors.

In [45]:
eigenvalues,eigenvectors=np.linalg.eig(cov_matrix)
print("Eigenvalues:")
print(eigenvalues)

Eigenvalues:
[1.13564827e+00 2.68507580e-06]

In [46]:
print("Eigenvectors:")
print(eigenvectors)

Eigenvectors:
[[ 9.99999614e-01  8.78753184e-04]
 [-8.78753184e-04  9.99999614e-01]]

5. Which wine quality is most common in the dataset? How can you interpret the distribution of wine quality scores?

In [47]:
qual_counts=df['quality'].value_counts()
print(qual_counts)

quality
5    681
6    638
7    199
4     53
8     18
3     10
Name: count, dtype: int64